- name: Télécharger Wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no

- name: Extraire Wordpress
  unarchive: 
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    copy: no
  become: yes
  become_user: web
    
- name: Renommer le dossier de Wordpress
  copy: 
    src: /var/www/wordpress/
    dest: /var/www/numeration/
    remote_src: true
    owner: web
    group: devops
    mode: 0775
  become: yes
  become_user: web

- name: Supprimer le précédent dossier de Wordpress
  file:
    path: /var/www/wordpress/
    state: absent
  become: yes
  become_user: web

- name: Supprimer le dossier de base d'Apache
  file:
    path: /var/www/html/
    state: absent
  become: yes

- name: Remplacer le fichier conf de wordpress
  copy:
    src: ./setup/wp-config.php
    dest: /var/www/numeration/
    force: true
  become: yes
  become_user: web

- name: Relancer le service apache  
  shell: "service apache2 restart"  