# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "mysql" do |mysql|
    mysql.vm.provider "virtualbox" do |vb_mysql|
      vb_mysql.memory = 1024
    end

    mysql.vm.box = "ubuntu/jammy64"
    mysql.vm.hostname = "mysql"
    mysql.vm.network "private_network", ip: "192.168.56.11"
    
    mysql.vm.provision "ansible" do |ansible|
     ansible.playbook = "../ansible/mysql/site.yml"
     ansible.compatibility_mode = "2.0"
    end
  end

  config.vm.define "web" do |web|
    web.vm.provider "virtualbox" do |vb_web|
      vb_web.memory = 1024
    end

    web.vm.box = "ubuntu/jammy64"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.56.10"
    web.vm.synced_folder "web_synced/", "/usr/local/synced_dir/"
    
    web.vm.provision "ansible" do |ansible|
     ansible.playbook = "../ansible/web/site.yml"
     ansible.compatibility_mode = "2.0"
    end
  end
end
